---
kind: pipeline
name: docker

trigger:
  branch:
    - main
  event:
    - cron
    - custom
    - push
  status:
    - success

steps:
  - name: qt6-headless
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.qt6-headless
      pull_images: true
      repo: ghcr.io/msrd0/qt6-headless
      cache_from: ghcr.io/msrd0/qt6-headless
      registry: ghcr.io
      username: msrd0
      password:
        from_secret: GHCR_TOKEN
      
  - name: mingw-qt6-static
    image: plugins/docker
    settings:
      repo: ghcr.io/msrd0/mingw-qt6-static
      registry: ghcr.io
      username: msrd0
      password:
        from_secret: GHCR_TOKEN
  
  - name: notify
    image: drillster/drone-email
    pull: always
    settings:
      host: smtp.migadu.com
      username: noreply@drone.msrd0.eu
      from: noreply@drone.msrd0.eu
      password:
        from_secret: SMTP_PASSWORD
    when:
      status:
        - failure

...
