---
kind: pipeline
name: docker

trigger:
  branch:
    - main
  event:
    - cron
    - custom
    - push
  status:
    - success

steps:
  - name: docker
    image: plugins/docker
    settings:
      pull_images: true
      repo: ghcr.io/msrd0/mingw-qt6-static
      registry: ghcr.io
      username: msrd0
      password:
        from_secret: GHCR_TOKEN

...
